name: demo-docker

services:
  mysql:
    image: groonga/mroonga:mysql-8.0.43-15.17
    container_name: demo-mysql
    restart: always
    networks:
      - demo-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
  redis:
    image: redis:6.2.21
    container_name: demo-redis
    restart: always
    networks:
      - demo-network
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
  dbgate:
    image: dbgate/dbgate:6.6.11
    container_name: demo-dbgate
    restart: always
    networks:
      - demo-network
    ports:
      - ${DBGATE_HOST_PORT}:${DBGATE_CONTAINER_PORT}
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.13.5
    container_name: demo-nginx-proxy-manager
    restart: always
    networks:
      - demo-network
    environment:
      TZ: Asia/Seoul
    ports:
      - ${NPM_HTTP_HOST_PORT}:${NPM_HTTP_CONTAINER_PORT}
      - ${NPM_HTTPS_HOST_PORT}:${NPM_HTTPS_CONTAINER_PORT}
      - ${NPM_ADMIN_HOST_PORT}:${NPM_ADMIN_CONTAINER_PORT}
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

networks:
  demo-network:
    driver: bridge