name: demo-docker

services:

  mysql:
    image: groonga/mroonga:mysql-8.0.44-15.21
    container_name: demo-mysql
    restart: unless-stopped
    networks:
      - demo-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/log:/var/log/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  redis:
    image: redis:6.2.21
    container_name: demo-redis
    restart: unless-stopped
    networks:
      - demo-network
    environment:
      TZ: Asia/Seoul
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    volumes:
      - ./docker/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  dbgate:
    image: dbgate/dbgate:6.8.1
    container_name: demo-dbgate
    restart: unless-stopped
    networks:
      - demo-network
    ports:
      - ${DBGATE_HOST_PORT}:${DBGATE_CONTAINER_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.13.5
    container_name: demo-nginx-proxy-manager
    restart: unless-stopped
    networks:
      - demo-network
    environment:
      TZ: Asia/Seoul
    ports:
      - ${NPM_HTTP_HOST_PORT}:${NPM_HTTP_CONTAINER_PORT}
      - ${NPM_HTTPS_HOST_PORT}:${NPM_HTTPS_CONTAINER_PORT}
      - ${NPM_ADMIN_HOST_PORT}:${NPM_ADMIN_CONTAINER_PORT}
    volumes:
      - ./docker/npm/data:/data
      - ./docker/npm/letsencrypt:/etc/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

networks:
  demo-network:
    driver: bridge