name: demo-docker

services:
  mysql:
    image: groonga/mroonga:mysql-8.0.43-15.17
    container_name: demo-mysql
    restart: unless-stopped
    networks:
      - demo-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
  redis:
    image: redis:6.2.21
    container_name: demo-redis
    restart: unless-stopped
    networks:
      - demo-network
    environment:
      TZ: Asia/Seoul
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}
    volumes:
      - ./redis/data:/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
  dbgate:
    image: dbgate/dbgate:6.6.11
    container_name: demo-dbgate
    restart: unless-stopped
    networks:
      - demo-network
    ports:
      - ${DBGATE_HOST_PORT}:${DBGATE_CONTAINER_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.13.5
    container_name: demo-nginx-proxy-manager
    restart: unless-stopped
    networks:
      - demo-network
    environment:
      TZ: Asia/Seoul
    ports:
      - ${NPM_HTTP_HOST_PORT}:${NPM_HTTP_CONTAINER_PORT}
      - ${NPM_HTTPS_HOST_PORT}:${NPM_HTTPS_CONTAINER_PORT}
      - ${NPM_ADMIN_HOST_PORT}:${NPM_ADMIN_CONTAINER_PORT}
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: demo-smtp4dev
    restart: always
    networks:
      - demo-network
    ports:
      - "5000:80"
      - "2525:25"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

networks:
  demo-network:
    driver: bridge